%YAML:1.0    #BT默认数据
---   
#初始化数据
init_armor_number: 0             # 识别到的装甲板的数量
init_armor_distance : 0        # 最近的装甲板的距离
init_armor_timestamp : 0.        # 装甲板时间戳
init_navigation_timestamp : 0.   # 导航事件戳
init_navigation_status : -1      # 导航状态,默认不处于任何一个地方
init_outpost_blood : 1000        # 前哨站血量
init_sentry_blood : 600          # 哨兵血量
init_bullet_num : 700            # 剩余子弹数目
init_time_left : 300             # 剩余比赛时间
init_game_timestamp : 0.         # 比赛状况事件戳
init_manual_top : 0              # 是否手动开启小陀螺
init_game_start : 0              # 默认比赛已经开启,true则已开始
init_m_alive : 2                 # 我方存活机器人
init_enemy_alive : 2             # 敌方存活机器人
init_position : -1               # 初始化不移动
init_hityaw : -1.                # 初始化时未被击打
#默认数据
armor_number: 0   
armor_distance : 0. 
outpost_blood : 1000 
sentry_blood : 600
time_left : 500 
bullet_num : 700 
manual_top : 1   
game_start: 1
m_alive : 2
enemy_alive : 2
position : 0                      # 收不到导航消息默认返回起始点
hityaw : -1
#出发点位置
start_position_x : 3.578902244567871
start_position_y : -3.01556658744812
start_position_z : 0
start_orientation_x : 0
start_orientation_y : 0
start_orientation_z : -0.3227323959072776
start_orientation_w : 0.9464902538494246
#补血点位置
resume_position_x : 3.578902244567871
resume_position_y : -3.01556658744812
resume_position_z : 1
resume_orientation_x : 1
resume_orientation_y : 1
resume_orientation_z : -0.3227323959072776
resume_orientation_w : 0.9464902538494246
#增益点位置
gain_position_x : 4.633669853210449
gain_position_y : 2.4196085929870605
gain_position_z : 2
gain_orientation_x : 2
gain_orientation_y : 2
gain_orientation_z : -0.9399724581924976
gain_orientation_w : 0.34125031551568313
#视界点位置
view_position_x : 0.20957046747207642
view_position_y : 0.2425970733165741
view_position_z : 3
view_orientation_x : 3
view_orientation_y : 3
view_orientation_z : -0.09327264668588802
view_orientation_w : 0.9956124546188632
