%YAML:1.0    #BT默认数据
---   
#初始化数据
init_armor_number: 0             # 识别到的装甲板的数量
init_armor_distance : 10.         # 最近的装甲板的距离
init_armor_timestamp : 0.        # 装甲板时间戳
init_navigation_timestamp : 0.   # 导航事件戳
init_navigation_status : 0       # 当前导航状态,true表示正在移动
init_navigation_back : 0         # 是否返回出发点
init_outpost_blood : 1000        # 前哨站血量
init_sentry_blood : 1000         # 哨兵血量
init_bullet_num : 700            # 剩余子弹数目
init_time_left : 300             # 剩余比赛时间
init_game_timestamp : 0.         # 比赛状况事件戳
init_manual_top : 0          # 是否手动开启小陀螺
#默认数据
armor_number: 1  
armor_distance : 1. 
outpost_blood : 1000 
sentry_blood : 1000
time_left : 500 
bullet_num : 700 
manual_top : 0  
navigation_back : 0 
navigation_status : 0     